-- AlterTable
ALTER TABLE `users` ADD COLUMN `passwordResetExpires` DATETIME(3) NULL,
    ADD COLUMN `passwordResetToken` VARCHAR(191) NULL,
    MODIFY `status` ENUM('INACTIVE', 'ACTIVE', 'SUSPENDED', 'REJECTED', 'PENDING') NOT NULL DEFAULT 'INACTIVE';
